driver:
  name: vagrant
  vagrantfiles:
    - ./test/.Vagrantfile.cachier.rb
    - ./test/.Vagrantfile.disable-berkshelf.rb

provisioner:
  name: chef_solo
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus

platforms:
<% %w(5.11 6.7 7.2).each do |version| %>
  - name: bento/centos-<%= version %>
<% end %>
  - name: bento/ubuntu-14.04
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[jetty::default]
    attributes:
