---
driver:
  name: docker

driver_config:
  require_chef_omnibus: false
  use_sudo: false
  privileged: true
  private_key: .kitchen/docker_id_rsa
  public_key: .kitchen/docker_id_rsa.pub

platforms:
<% %w(5.11 6.7 7.2).each do |version| %>
  - name: centos-<%= version %>
    driver_config:
      volume:
      <% if File.exist?("#{ENV['HOME']}/.vagrant.d/cache/bento/centos-#{version}") %>
        - <%= ENV['HOME'] %>/.vagrant.d/cache/bento/centos-<%= version %>/chef:/var/chef/cache
        - <%= ENV['HOME'] %>/.vagrant.d/cache/bento/centos-<%= version %>/vagrant_omnibus:/tmp/vagrant-cache/vagrant_omnibus/
        - <%= ENV['HOME'] %>/.vagrant.d/cache/bento/centos-<%= version %>/yum:/var/cache/yum
      <% end %>
      provision_command:
        - yum makecache && yum -y install autoconf bison flex gcc gcc-c++ kernel-devel make m4 curl tar
        - curl -L https://www.opscode.com/chef/install.sh | bash -s -- -v 11.18.12 -d /tmp/vagrant-cache/vagrant_omnibus/
        - env GEM_HOME=/tmp/verifier/gems GEM_PATH=/tmp/verifier/gems GEM_CACHE=/tmp/verifier/gems/cache /opt/chef/embedded/bin/gem install --no-ri --no-rdoc net-ssh -v '2.9.2'
        - env GEM_HOME=/tmp/verifier/gems GEM_PATH=/tmp/verifier/gems GEM_CACHE=/tmp/verifier/gems/cache /opt/chef/embedded/bin/gem install --no-ri --no-rdoc thor busser busser-serverspec serverspec bundler cucumber rspec-expectations
        - chown -R kitchen:kitchen /tmp/verifier
    <% if version.to_f >= 7.0 %>
      run_command: /usr/lib/systemd/systemd
    <% end %>
<% end %>
  - name: ubuntu-14.04
    driver_config:
      volume:
      <% if File.exist?("#{ENV['HOME']}/.vagrant.d/cache/bento/ubuntu-14.04") %>
        - <%= ENV['HOME'] %>/.vagrant.d/cache/bento/ubuntu-14.04/apt:/var/cache/apt/archives
        - <%= ENV['HOME'] %>/.vagrant.d/cache/bento/ubuntu-14.04/chef:/var/chef/cache
        - <%= ENV['HOME'] %>/.vagrant.d/cache/bento/ubuntu-14.04/vagrant_omnibus:/tmp/vagrant-cache/vagrant_omnibus/
      <% end %>
      provision_command:
        - curl -L https://www.opscode.com/chef/install.sh | bash -s -- -v 11.18.12 -d /tmp/vagrant-cache/vagrant_omnibus/
        - env GEM_HOME=/tmp/verifier/gems GEM_PATH=/tmp/verifier/gems GEM_CACHE=/tmp/verifier/gems/cache /opt/chef/embedded/bin/gem install --no-ri --no-rdoc net-ssh -v '2.9.2'
        - env GEM_HOME=/tmp/verifier/gems GEM_PATH=/tmp/verifier/gems GEM_CACHE=/tmp/verifier/gems/cache /opt/chef/embedded/bin/gem install --no-ri --no-rdoc thor busser busser-serverspec serverspec bundler cucumber rspec-expectations
        - chown -R kitchen:kitchen /tmp/verifier
